In [1]:
import numpy as np

In [2]:
a = np.array([1])
a

array([1])

In [3]:
print(a)
a.shape

[1]


(1,)

In [4]:
b = np.array([[1.145]])
b.shape

(1, 1)

In [5]:
b.ndim

2

In [6]:
a.ndim

1

In [7]:
matrix = np.array([[1,2,3],[2,3,4]])
matrix

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

(2, 3)

In [10]:
# Create a 5x4 matrix
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
d[0]

array([1, 2, 3, 4])

In [11]:
d = matrix[0]
d

array([1, 2, 3])

In [12]:
d.ndim

1

In [13]:
d.shape

(3,)

In [14]:
# Extract through 
d = matrix[:][1]
d

array([2, 3, 4])

In [15]:
d.ndim

1

In [16]:
a = np.zeros((3,3))
b = np.ones((2,3))
y = np.vstack((a,b))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
y = np.zeros((3,3)),np.ones((2,3))
y

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [18]:
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
# b = np.array([a[0,0],a[1,1],a[2,2]])
# b
b = (a[[0,1,2] ,[0,1,2]])
b
b.ndim

1

In [19]:
t = np.array([a[[0,1,2],[2,1,2]]])
t.ndim

2

In [20]:
A = np.array([[10,-2,1,0],[3,5,-7,22],[4,-1,-3,16],[0,5,8,-9]])
A

array([[10, -2,  1,  0],
       [ 3,  5, -7, 22],
       [ 4, -1, -3, 16],
       [ 0,  5,  8, -9]])

## Boolean Indexing

In [21]:
A = np.array([[-1.2,1.7,2.5,0.8],
              [3.7,-6.2,0.9,1.5],
              [-2.6,-3.2,4.7,5.2],
              [0.5,2.2,1.8,-2.1]])
A

array([[-1.2,  1.7,  2.5,  0.8],
       [ 3.7, -6.2,  0.9,  1.5],
       [-2.6, -3.2,  4.7,  5.2],
       [ 0.5,  2.2,  1.8, -2.1]])

In [22]:
A>1

array([[False,  True,  True, False],
       [ True, False, False,  True],
       [False, False,  True,  True],
       [False,  True,  True, False]])

In [23]:
A == 2.2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [24]:
A > 0

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True, False]])

In [25]:
(-1 <= A) ^ (A <= 1)

array([[ True,  True,  True, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [26]:
~(A>1) # or A<= 1

array([[ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True, False, False],
       [ True, False, False,  True]])

In [27]:
A<=1

array([[ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True, False, False],
       [ True, False, False,  True]])

In [28]:
B = A[A>1] # Get the values where the position is fulfilled
B

array([1.7, 2.5, 3.7, 1.5, 4.7, 5.2, 2.2, 1.8])

In [29]:
B = A[A<0]
B

array([-1.2, -6.2, -2.6, -3.2, -2.1])

In [30]:
# checking datatype

A.dtype

dtype('float64')

In [31]:
A.dtype = np.float16
A.dtype

dtype('float16')

In [32]:
X = np.array([[1,2],
              [3,4]])
X.dtype

dtype('int64')

In [33]:
Y = np.array([[1.0,2.0],
              [3.0,4.0]])
x.dtype

NameError: name 'x' is not defined

In [ ]:
X-Y

In [ ]:
X+Y
# Or 
np.add(X,Y)

In [ ]:
X/Y
# or
np.divide(X,Y)

In [ ]:
np.multiply(X,Y) # or x*y #This is not maatrix multiplication

In [ ]:
np.dot(X,Y) # Dot product
X@Y

In [ ]:
np.sqrt(X)

In [ ]:
np.log(X)  #natural log

In [ ]:
np.log10(X)

In [ ]:
np.square(X)

In [ ]:
e = np.exp(X)
e

In [ ]:
np.sin(X)

In [ ]:
np.arctan(X)

In [ ]:
np.mean(X)

In [ ]:
np.var(X)

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

np.sum(A,axis=0)

In [ ]:
np.mean(A,axis=0)

In [ ]:
np.transpose(A)
A.T

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [ ]:
B = np.array([[1,0,-1]]) # Row wise addition by briadcasting
A+B

In [ ]:
B = np.array([[1],[0],[-1]]) # Col wise addition by Broaadcasting
A+B

In [ ]:
A = np.array([[1,2,3,4,5],
              [4,5,6,7,8]])
A.reshape(2,5)
A.reshape(5,2)
#OR
np.reshape(A,(10,1))

A.reshape(2,-1) # if do not know size 

In [ ]:
L = np.random.random((8,3))
L

In [ ]:
np.reshape(L,(6,-1))

## 3-D 

In [ ]:
X = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11 ,12]]])
print(X)

In [ ]:
X.ndim

## Exploring picture as a matrix

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
image_path = 'me.jpg'

In [ ]:

my_image = Image.open(image_path)
my_image

In [ ]:
my_image_arrray = np.array(my_image)
my_image_arrray
my_image_arrray.shape

In [ ]:
plt.imshow(my_image_arrray)
plt.show()

In [ ]:
im1 = np.fliplr(my_image_arrray)
plt.imshow(im1)

In [ ]:
im2 = np.flipud(my_image_arrray)
plt.imshow(im2)
plt.show()

In [ ]:
im3 = np.resize(my_image_arrray,(4000,2250,3))
plt.imshow(im3)
plt.show

In [ ]:
np.max(my_image_arrray)

In [ ]:
im4 = np.clip(my_image_arrray,50,255)
plt.imshow(im4)